SimpleMobileTools/Simple-Calculator

app/src/main/java/com/simplemobiletools/calculator/CalculatorImpl.java, app/src/main/java/com/simplemobiletools/calculator/operation/DivideOperation.java, app/src/main/java/com/simplemobiletools/calculator/operation/MinusOperation.java, app/src/main/java/com/simplemobiletools/calculator/operation/ModuloOperation.java, app/src/main/java/com/simplemobiletools/calculator/operation/MultiplyOperation.java, app/src/main/java/com/simplemobiletools/calculator/operation/OperationFactory.java, app/src/main/java/com/simplemobiletools/calculator/operation/PlusOperation.java, app/src/main/java/com/simplemobiletools/calculator/operation/PowerOperation.java, app/src/main/java/com/simplemobiletools/calculator/operation/RootOperation.java, app/src/main/java/com/simplemobiletools/calculator/operation/base/BinaryOperation.java, app/src/main/java/com/simplemobiletools/calculator/operation/base/Operation.java, app/src/main/java/com/simplemobiletools/calculator/operation/base/UnaryOperation.java
I started splitting CalculatorImpl into many independent classes because it is too big. It's hard to realize what is going on there. Please, don't be afraid of so many changes: *all tests are green, I swear.*
If you feel something is really wrong with my code, please, tell me. I'm going to start fixing some bugs in calculator, so I'll do my best to polish it and to improve its readability. Thank you!
=> Polymorphic calculator operations

app/src/main/res/values-de/strings.xml
Added translation for button vibration.
=> Updated German localization

app/src/main/kotlin/com/simplemobiletools/calculator/helpers/CalculatorImpl.kt
I believe its not the best idea to have two variables ( mBaseValue , mSecondValue ) for calculation. I found a solution without changing that but i think we have to refactor CalculatorImpl.kt in the future.
=> Confusing behaviour after calculating a square root #28

app/src/main/kotlin/com/simplemobiletools/calculator/helpers/CalculatorImpl.kt, app/src/main/kotlin/com/simplemobiletools/calculator/helpers/Constants.kt
=> [Bug] NaN error #54

app/src/main/res/values-fr/strings.xml
Hi again,
I updated and fixed the French translation. 
I replaced the term "calculette" with "calculatrice". While the two are valid in French, French people would typically search for a "calculatrice" in an app store.
=> Updated and fixed French translation

app/src/main/res/values/strings.xml
- proposed FAQ entry for the C button.
- updated http:// to https:// as done at other Simple Tools.
please accept or reject the change, i will make the Dutch translation next to match your decision.
=> Simple Calculator - Update strings.xml

app/src/main/res/values-ar/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh-rTW/strings.xml
- created Dutch translation
- added English FAQ entry to all language files.
=> created Dutch translation / added English FAQ entry to all language files.

app/src/main/res/values-pl/strings.xml
I think it was missed / ignored during my last translation "tour", so I'm redoing it.
=> PL translation updates [2018.06.27]

app/src/main/res/values-ru/strings.xml
=> Update strings.xml, fix typo

app/src/main/res/values-it/strings.xml
Hi! I'm revisioning all translations, improving the quality of all strings. This is the first app I've checked.
=> Improve italian translations

app/src/main/res/values-ru/strings.xml
=> minor translation improvements (Russian)

app/src/androidTest/java/com/simplemobiletools/calculator/MainActivityTest.java, app/src/main/kotlin/com/simplemobiletools/calculator/helpers/CalculatorImpl.kt
The commented lines in gradle.
=> Resolve the bug of C and add a test case

app/src/main/res/values-zh-rCN/strings.xml
=> Add zh_CN translated strings.xml.

app/src/main/res/values-kr/strings.xml
Added Korean language support for the application and the description.
Suitable changes of the description have been made but the general meaning still lies therein.
=> Created strings.xml for Korean Language

app/src/main/res/values-my/strings.xml
Added Malay Language for Simple-Calculator
=> Translation: Add Malay Language(values-my/strings.xml)

app/src/main/res/values-ms/strings.xml
Update of Malay Translation. Sorry for the exceed of characters in app title and short description.
=> Translation: Update of Malay Translation(value-ms/strings.xml)

app/src/main/res/values-it/strings.xml
See https://github.com/SimpleMobileTools/Simple-Music-Player/pull/264 for more information.
=> Update Italian translator

app/src/main/res/values-he/string.xml
Closes #215 
String started with '?' at the start which Android sees as a reference to a resource value, added a backslash so it is seen as a question mark
=> added backslash to escape '?'

app/src/main/kotlin/com/simplemobiletools/calculator/helpers/CalculatorImpl.kt
Fixes #228
**Before:**
https://user-images.githubusercontent.com/85929121/144727876-10814e06-084f-497f-b2b4-577cf9ec2ff5.mp4
**After:**
https://user-images.githubusercontent.com/85929121/144727881-44d94123-e529-4d9a-86e9-938728735e67.mp4
=> Fixed large number percentage error (#228)

app/src/main/kotlin/com/simplemobiletools/calculator/helpers/CalculatorImpl.kt
Fixes #202
**Before:**
https://user-images.githubusercontent.com/85929121/144741364-730fb8ec-3715-45e1-9bad-b2ae366d35c7.mp4
**After:**
https://user-images.githubusercontent.com/85929121/144741367-afa4247a-8966-4248-98b3-1d5e5a3c6c00.mp4
=> Fixed changing operator after dividing by zero (#202)

app/src/main/AndroidManifest.xml, app/src/main/kotlin/com/simplemobiletools/calculator/helpers/Config.kt, app/src/main/kotlin/com/simplemobiletools/calculator/helpers/NumberFormatHelper.kt, app/src/main/kotlin/com/simplemobiletools/calculator/receivers/LocaleChangeReceiver.kt
https://user-images.githubusercontent.com/36371707/172995878-644dd378-3d0d-4fbd-b0ce-72eeaa20a4d3.mp4
=> Use device locale's decimal separator by default
